### ISSUE TITLE
Parameters and Tags as Files

### ISSUE THREAD

**Issue by Pkamis** [aws-cloudformation/rain#11]
Have you considered supporting parameters/tags as optional input json/yml files for the deploy command?

For complex templates, it's cumbersome to input all the parameters/tags on the command line.

**Comment by stilvoid** [comment]
Hi, yes I am definitely planning to do this quite soon. In fact, I'm experimenting with using a more fully-featured input file to cover parameters, tags, and deployment of multiple stacks in multiple regions. Watch this space.

**Comment by cfbarbero** [comment]
Can I suggest that you support the same format as [CodePipeline](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/continuous-delivery-codepipeline-cfn-artifacts.html#w2ab1c13c17c15)?  This makes it easy to test your cloudformation stacks with the same configuration you use in CodePipeline.

```
{
  "Parameters" : {
    "NameOfTemplateParameter" : "ValueOfParameter",
    ...
  },
  "Tags" : {
    "TagKey" : "TagValue",
    ...
  }, 
  "StackPolicy" : {
    "Statement" : [
      StackPolicyStatement
    ]
  }
}
```

**Comment by stilvoid** [comment]
You read my mind :)

**Comment by Marakai** [comment]
I had vague hopes that the 0.8.0 branch might have this feature and I would have gone a bravely tested it - but it seems it's not the case?

**Comment by stilvoid** [comment]
`v0.8.0` adds parameter and tag options to the deploy command but doesn't yet have support for configuration from files. I'm intending to add that soon.

**Comment by almorelle** [comment]
👍🏼

**Comment by mokele** [comment]
https://github.com/mokele/template-configuration for CodePipeline Template Configuration format across all 3 major tools `aws`, `sam`, and `rain` :)

**Comment by stilvoid** [comment]
This is merged to `main` and will be in the next release (soon) :)
