### ISSUE TITLE
"nocgo" variant missing from newer releases

### ISSUE THREAD

**Issue by dhutchison** [aws-cloudformation/rain#129]
v1.2.0 was the last version that included "-nocgo" variants in the release. I believe these were added to fix #17.

Was this an intentional removal? I've tried the normal amd64 release of 1.3.3 in an alpine container and I get the same error as seen in that issue. If I roll back to amd64-nocgo 1.2.0 rain works as expected.

**Comment by ericzbeard** [comment]
This may have been dropped when we created (or changed) the [release action](https://github.com/aws-cloudformation/rain/blob/main/.github/workflows/release.yml).

**Comment by ericzbeard** [comment]
https://github.com/aws-cloudformation/rain/releases/tag/v1.4.0

Please let me know if the nocgo variant works as expected.
