### ISSUE TITLE
Cannot convert to json using fmt

### ISSUE THREAD

**Issue by edgdelgado** [aws-cloudformation/rain#134]
Hi,
Im trying to convert a cf template from yaml to json but im getting this error:

rain.exe fmt wa_ent_net.yml -j -w
semantic difference after formatting:
(|) Conditions:
(>)   Cond3AZ:
(>)     - - Ref: NumAZs
(>)       - 3
(>)     - Fn::Condition: Cond4AZ
(>)   Cond4AZ:
(>)     - Ref: NumAZs
(>)     - 4
(|)   CondNATGateway:
(-)     Condition: ...
(+)     Fn::Condition: CondPrivateSubnet
(>)   CondNATGateway&3AZ:
(>)     - Fn::Condition: CondPrivateSubnet
(>)     - Fn::Condition: Cond3AZ
(>)   CondNATGateway&4AZ:
(>)     - Fn::Condition: CondPrivateSubnet
(>)     - Fn::Condition: Cond4AZ
(>)   CondNVirginiaRegion:
(>)     - Ref: AWS::Region
(>)     - us-east-1
(>)   CondPrivateSubnet:
(>)     - Ref: CreatePrivateSubnets
(>)     - true
(>)   CondPrivateSubnet&3AZ:
(>)     - - Ref: CreatePrivateSubnets
any sugestions?

template:

**Comment by ericzbeard** [comment]
Can you include a copy of the template?

**Comment by edgdelgado** [comment]
> Can you include a copy of the template?

Hi! yes...
https://wa-biz-cfn.s3.amazonaws.com/wa_ent_net.yml 

it feels like its something about the nested conditions in CF

**Comment by ericzbeard** [comment]
I can't replicate locally so this might be resolved on main but not released yet.
