### ISSUE TITLE
Warn instead of panic about unknown parameters

### ISSUE THREAD

**Issue by ugwis** [aws-cloudformation/rain#144]
It's implemented to fail if there are unknown parameters when deploying,
```
$ cat test.yaml 
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  VPC1CIDR:
    Type: String
    Default: "10.0.0.0/16"
Resources:
  Param1:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "param1"
      Type: String
      Value: "value1"
```
```
$ cat config.yaml 
Parameters:
  KeyPair: tokyo
```

![Screenshot 2023-06-01 at 14 22 23](https://github.com/aws-cloudformation/rain/assets/914815/1d94ce9d-de4f-46c7-a012-f5dbed215e14)
but I think it's enough to warn about unknown parameters.

This is because changing it to a warning lets you specify parameters commonly used by multiple templates in one configuration file. 
For example, if one requires a public key, another requires a public key and certificate, and another requires a certificate parameter, then deploy templates with one configuration file that specifies the certificate and public key parameters.

## proposal
Warning instead of panic and continue processing.
![Screenshot 2023-06-01 at 14 38 08](https://github.com/aws-cloudformation/rain/assets/914815/7ece70bc-05b5-4149-8021-5598227f26a8)

**Comment by ericzbeard** [comment]
I wonder if some users might depend on this to fail if they mistype a parameter? Could be seen as a regression. Would it be better to make it configurable? For example, `--ignore-unknown-params`.

**Comment by ugwis** [comment]
If it's okay to add a flag for this, I think it's safer.

example)
```
$ rain deploy test.yaml
unknown parameter: KeyPair (if you want to proceed as is, add the --ignore-unknown-params flag)
$ rain deploy test.yaml --ignore-unknown-params
unknown parameter: KeyPair 
...
```

Alternatively, there is a way to change it only to warn if -y, but that can also be a bit destructive.

**Comment by ugwis** [comment]
Close because it was merged.
Thank you.
