### ISSUE TITLE
common.formatString eats leading spaces

### ISSUE THREAD

**Issue by mdaniel** [aws-cloudformation/rain#15]
# What

A `Fn::Join` which contains leading spaces strips the leading space, making `rain fmt` angry:
```console
$ cat > foo.yml<<"YML"
Outputs: "  hello\n"
YML
$ rain fmt foo.yml
Semantic difference after formatting:
(>) Outputs: hello
```

That is just the silly reproducible case, my actual case looks like:
```yaml
UserData:
  Fn::Base64:
    Fn::Join:
    - ""
    - - "  something="
      - !GetAtt MyRes.MyAtt
      - "  else\n"
```

It is being _parsed_ correctly, it's just the YAML render that is incorrect:
```console
$ rain fmt -j foo.yml
{
    "Outputs": "  hello\n"
}
```

# Why

`formatString` assumes that any string containing a newline can be converted into an equivalent yaml "pipe block", but (a) it [explicitly calls `TrimSpace`](https://github.com/aws-cloudformation/rain/blob/85e77f4f1ef5585db968ed5581088440adf03bcd/cfn/format/common.go#L26) and (b) even if it didn't, yaml pipe blocks use the first _non whitespace_ character to establish the start of content, so one cannot represent that `Outputs:` using only `: |` syntax

**Comment by stilvoid** [comment]
Fixed in `master` and will be in `v0.8.1`
