### ISSUE TITLE
Gantt Chart

### ISSUE THREAD

**Issue by jsutton** [aws-cloudformation/rain#158]
When I use rain, it would be nice to see the order and duration of stack execution. This would help with troubleshooting long running stacks. There is a python program that does something like this: https://github.com/jaredtrog/cfplot

**Comment by ericzbeard** [comment]
Is this something you would want to see output into the console as you wait for a deployment to complete? Or are you only interested in seeing it after everything is finished?

**Comment by jsutton** [comment]
I am most interested in seeing the information after the run is finished, as I use it to refactor stacks to run in less time. Maybe something like a plot subcommand. 

I can also see some utility in a realtime visualization to see where a stack may be hung, but the existing output is ok.

**Comment by ericzbeard** [comment]
I'm thinking of building this into the existing `logs` command, with a new option `--chart`. 

A related feature would be an option to both the `deploy` and `watch` commands to output a running log of events instead of the spinner, I think `--verbose` would make sense for that one. I'll create a separate issue for those.

**Comment by ericzbeard** [comment]
This is what the prototype looks like:

`rain logs --chart CDKToolkit  > ~/Desktop/chart.html`

![image](https://github.com/aws-cloudformation/rain/assets/663183/4cde93a6-fe5c-4355-9fa1-811491391d1d)

**Comment by ericzbeard** [comment]
@jsutton Let me know what you think of this.

**Comment by jsutton** [comment]
Looks great! I’ll ask a few colleagues as well.
