### ISSUE TITLE
Semantic difference mangles multiline output

### ISSUE THREAD

**Issue by mdaniel** [aws-cloudformation/rain#16]
# What

```console
$ cat > foo.yml<<"YML"
Outputs:
- "  alpha\n"
- beta
YML
$ rain fmt foo.yml
Semantic difference after formatting:
(|) Outputs:
(>)   [0]: |
  a  lpha
```

This is just a diff formatting bug, but it does make one worry why some strings have random whitespace in the middle of a user-data expression in the `rain fmt` output

# Why

`formatSub` is doing some slice wizardry which does not take multiline strings into account
```go
part = part[:len(diff.Added.String())] + indent + part[len(diff.Added.String()):]
```

**Comment by stilvoid** [comment]
Fixed in `master` and will be in `v0.8.1`
