### ISSUE TITLE
Rain fmt after v1.3.3 has removed spaces

### ISSUE THREAD

**Issue by lesterjude** [aws-cloudformation/rain#161]
Why are spaces removed after running `rain fmt -wu template.yaml` in between the Cloudformation Template Sections like Description, Conditions, Parameters (and each and every parameters) and Resources?

I have observed this after v.1.3.3. 
Is there a way to retain the spaces as per our preferences by passing an additional parameter or via configuration file perhaps?

**Comment by ugwis** [comment]
Do you mean trailing space in Section name line?
![Screenshot 2023-06-21 at 9 00 35](https://github.com/aws-cloudformation/rain/assets/914815/b48832ca-9743-4cc4-a845-656d3fae2d27)
![Screenshot 2023-06-21 at 9 00 39](https://github.com/aws-cloudformation/rain/assets/914815/ae0a3f34-7a75-4450-b8f0-3ad42d87dbe9)
There is no option to preserve it.

If you meant trailing spaces in the value string, you could keep them by quoting.
![Screenshot 2023-06-21 at 9 08 54](https://github.com/aws-cloudformation/rain/assets/914815/431ff963-37b7-44e0-8607-15dc2baafc21)
![Screenshot 2023-06-21 at 9 08 58](https://github.com/aws-cloudformation/rain/assets/914815/0dd83378-2cbc-490c-ae18-501cefc18c02)

**Comment by lesterjude** [comment]
Hi @ugwis, I meant spaces between the Sections themselves
this template
![image](https://github.com/aws-cloudformation/rain/assets/1168973/e435f5dd-6d9c-4842-8931-bd803ab5db55)
becomes
![image](https://github.com/aws-cloudformation/rain/assets/1168973/6b422948-a1f9-43ce-96b6-bb237fcf910f)
after rain fmt -wu template.yaml

**Comment by ugwis** [comment]
Thank you for reporting!
There was incorrect handling at multi-line value.
```
$ rain fmt template.yaml
AWSTemplateFormatVersion: "2010-09-09"

Description: |
  Test template
Parameters:
  ApiNames:
    Type: String
Resources:
  DashboardTest:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: Test
      DashboardBody: Test
```
