### ISSUE TITLE
Forecast: Displays message to provide parameters or run with --yes but Forecase does not accept --yes

### ISSUE THREAD

**Issue by stilvoid** [aws-cloudformation/rain#168]
When running forecast with a template containing parameters, if you do not supply parameter values, you get the message (from rain deploy) `no default or existing value for parameter '<param>'. Set a default, supply a --params flag, or deploy without the --yes flag`.

`rain forecast` does not accept either --yes or --params flags (at least they're not listed in `rain forecast --help`).

**Comment by ericzbeard** [comment]
What version are you on? I just confirmed this works locally:

`rain forecast -x --params BucketName=abc test/templates/forecast-ref.yaml fref`

**Comment by stilvoid** [comment]
This is on current `main` which reports v1.4.2:

```
go run cmd/rain/main.go forecast -x --yes test/templates/forecast-ref.yaml fref -p sengledo
Error: unknown flag: --yes
```

`--params` is there, my mistake, it's just --yes that's missing. --yes is also not listed if you run `rain forecast --help`

**Comment by ericzbeard** [comment]
I don't think `--yes` is necessary for forecast. Is it?
