### ISSUE TITLE
[Feature Request] Add rain to the official Amazon Linux 2 / 2023 software repository

### ISSUE THREAD

**Issue by r-heimann** [aws-cloudformation/rain#190]
See title, it would be awesome to add/remove/modify rain through the official Amazon Linux 2 / 2023 software repository.

**Comment by ugwis** [comment]
Hi.
Please submit your package request using the link below.
https://github.com/amazonlinux/amazon-linux-2023/issues/new/choose

**Comment by r-heimann** [comment]
Got it

**Comment by r-heimann** [comment]
Issue opened: https://github.com/amazonlinux/amazon-linux-2023/issues/435
