### ISSUE TITLE
Add new option to specify the time range using `rain logs`

### ISSUE THREAD

**Issue by r-heimann** [aws-cloudformation/rain#192]
It would be awesome to have a new option for `rain logs` to specify the time range that the logs should be printed. Currently every single log of the stack is printed when you use `rain logs`. If you have a crapton of logs, it will print all of them.

An option like `--range 30` (days) would be great.

**Comment by r-heimann** [comment]
Be aware that we are planning to create a Pull Request for this feature, i just wanted to write this down for future reference. It might take some time until we create the pr, since we are not familiar with coding in Go.

**Comment by hariprakash-j** [comment]
hi @ericzbeard this seems to be open for a while and I like to work on it , but i have one question. Wouldn't it be better to change the range to a number of log entries (starting from the latest) instead of time ? I feel using time as a metric to reduce the number of logs displayed is not good, it might not give the intended result when some one wants to check the log as cfn stacks are run so sparingly and would be harder to implement than the simple range with number of logs. Let me know what you think about this.

**Comment by r-heimann** [comment]
> hi @ericzbeard this seems to be open for a while and I'd like to work on it , but i have one question. Wouldn't it be better to change the range to a number of log entries (starting from the latest) instead of time ? I feel using time as a metric to reduce the number of logs displayed is not good, it might not give the intended result when some one wants to check the log as cfn stacks are run so sparingly and would be harder to implement than the simple range with number of logs. Let me know what you think about this.

Sorry for not being able to work on this, too much else needs my attention right now but i was hoping to take a look at this at the end of the year.

I personally wouldn't use the `number of log entries` option, since you never really know how many log entries a create/update/remove operation would produce. imo the best implementation of this feature would be to only display the "new" log entries that have been caused by the create/update/remove. In a pipeline you usually only want to see relevant information, and this is the one that i would be most interested in. But i honestly don't know if i have the skills to code that with Go, so i was looking at the time range option.

**Comment by hariprakash-j** [comment]
> Why not both? We could have a number of different flags. `--range-from` and `--range-to`, or `--range-days`, `--num-entries`, etc.

yea that should be doable, created a pr for the same. I named the flags a bit different but let me know if you'd like to change them

**Comment by r-heimann** [comment]
Fixed in https://github.com/aws-cloudformation/rain/pull/209
