### ISSUE TITLE
Format: Show the expected template

### ISSUE THREAD

**Issue by ugwis** [aws-cloudformation/rain#196]
`gopkg.in/yaml.v3` package generates templates without preserving the styles of the original template and causes some issues. #110 #126 
Even with the `--debug` option, users cannot know which templates are expected.

Plan A:
Show expected template with `--debug` option

Plan B:
Add another option to display expected templates

**Comment by ericzbeard** [comment]
Not sure what you mean by "expected template".

**Comment by ugwis** [comment]
Sorry, that was inaccurate.

Correctly, when `parse.Verify` fails, the following error occurs, but the user has no choice but to raise an issue and wait for the result.
However, if `parse.Verify` fails; this is often a corner case of the original template, and the user simultaneously can raise an issue and get a workaround by checking the formatting [res.output](https://github.com/aws-cloudformation/rain/blob/8ae62def1064cbd2efadf16f64c57c0ca12aee88/internal/cmd/fmt/fmt.go#L50)

```
$ rain fmt t.yaml
semantic difference after formatting:
(|) Resources:
(|)   LaunchConfig:
(|)     Metadata:
(|)       AWS::CloudFormation::Init:
(|)         config:
(|)           files:
(|)             /etc/cfn/cfn-hup.conf:
(|)               content:
(|)                 Fn::Join:
(|)                   [1]:
(>)                     [3]: ""
(>)                     [6]: ""
(|)             /etc/cfn/hooks.d/cfn-auto-reloader.conf:
(|)               content:
(|)                 Fn::Join:
(|)                   [1]:
(>)                     [9]: ""
(|)             /var/www/html/index.html:
(|)               content:
(|)                 Fn::Join:
(>)                   [0]: |2+
```

In that respect, expanding the --debug option seems good.

**Comment by ericzbeard** [comment]
Ok, so you want to do something like `config.Debugf("formatted output:\n%vres.output")`

**Comment by ugwis** [comment]
Thank you!
