### ISSUE TITLE
Rewrite in python in include in AWS CLI

### ISSUE THREAD

**Issue by hauboldj** [aws-cloudformation/rain#2]

**Comment by stilvoid** [comment]
I can't tell if you're joking but thanks for the vote of confidence :)

The AWS CLI and Rain have fairly different goals and I think they make sense as independent tools. Now, if you want to convince the AWS CLI team to rewrite in Go... that's a different story :D

**Comment by hauboldj** [comment]
No, totally serious. I think you would get a lot more traction if this was part of the CLI. I think of it as similar to how the cli provides the `s3` and `s3api` interface.
