### ISSUE TITLE
Use standard Go platform names in release artifacts

### ISSUE THREAD

**Issue by cacack** [aws-cloudformation/rain#201]
Currently the releases are named `macos` for Mac.  However, Go uses `darwin` which matches the output from `uname`.

```
❯ go version
go version go1.21.1 darwin/arm64

❯ go tool dist list | grep macos

❯ go tool dist list | grep darwin
darwin/amd64
darwin/arm64

❯ uname -s
Darwin
```

Please use `darwin` in release artifacts for Mac.

**Comment by cacack** [comment]
This similar to my other problems with consuming the artifacts on Apple silicon noted in #151

**Comment by ericzbeard** [comment]
I wonder if we might break someone who relies on the names as they are.

**Comment by ericzbeard** [comment]
Any chance you could create a PR for the [build script](https://github.com/aws-cloudformation/rain/blob/main/.github/workflows/build.sh)?

**Comment by cacack** [comment]
PR has both naming change and build for darwin/arm64.

I can see how this change in naming could break existing users.  I could deal with this on my side; just prefer to align on "standard" naming if possible.  Let me know what you think and I can adjust the PR accordingly.
