### ISSUE TITLE
Add changeset functionality to rain

### ISSUE THREAD

**Issue by ericzbeard** [aws-cloudformation/rain#212]
### Discussed in https://github.com/aws-cloudformation/rain/discussions/210

<div type='discussions-op-text'>

<sup>Originally posted by **isavcic** November 16, 2023</sup>
Is there a way to only create the change-set, and is there a way to apply the previously created change-set?</div>

**Comment by ericzbeard** [comment]
There is a lot of interesting functionality in changesets that rain could wrap. This was announced today: https://aws.amazon.com/about-aws/whats-new/2023/11/aws-cloudformation-import-parameter-changesets/

**Comment by isavcic** [comment]
This is, in my opinion, a great feature to have, as it allows you to create and apply the ChangeSet in different CI stages, allows manual approvals of a ChangeSet, automated parsing of ChangeSet before approval and so forth.
