### ISSUE TITLE
Unable to install rain - Linux

### ISSUE THREAD

**Issue by tech-novic** [aws-cloudformation/rain#218]
While installing rain getting this error

build github.com/aws-cloudformation/rain/cmd/rain: cannot load archive/zip: malformed module path "archive/zip": missing dot in first path element

Go version go1.13.8 linux/amd64

**Comment by khmoryz** [comment]
Maybe, the Go version is too old.

I tried go1.13.8, and then I got a similar message.

`build github.com/aws-cloudformation/rain/cmd/rain: cannot load embed: malformed module path "embed": missing dot in first path element`

Try to use Go 1.18.10 or later.
In my Docker environment, I installed rain successfully.

Verification:

```sh
$ docker pull golang:1.18
$ docker run -it --rm golang:1.18 /bin/bash
root@c88d47fe047d:/go# go version
go version go1.18.10 linux/amd64
root@c88d47fe047d:/go# GO111MODULE=on go install github.com/aws-cloudformation/rain/cmd/rain@latest
root@c88d47fe047d:/go# ./bin/rain --help 
Rain is a command line tool for working with AWS CloudFormation templates and stacks

Usage:
  rain [command]

...omit
```

Reason:
https://github.com/aws-cloudformation/rain/blob/82d08297fa7efdd41e64f502f58b0cf9d416a0ee/go.mod#L3

**Comment by ericzbeard** [comment]
@khmoryz is correct, need to update the Go version.
