### ISSUE TITLE
rain should support "service-managed" stacksets

### ISSUE THREAD

**Issue by paul-e-allen** [aws-cloudformation/rain#277]
I am deploying CloudFormation templates that create stacksets as resources. I thought I might be able to use the `rain stackset ls TARGET_STACKSET` to watch the deployment of the stacksets. 

When I executed just a plain `rain stackset ls` I noticed that `rain` is showing only the "self-managed" stacksets and not the "service-managed" stacksets. 

When I try to execute a `rain stackset ls TARGET_STACKSET` when the target stackset is "service-managed", that generates the following error:

```
failed to list stack set 'stacksets-gitsync-test-team-chatbot-limited-regions-regional': operation error CloudFormation: DescribeStackSet, https response error StatusCode: 404, RequestID: 0d95366b-8326-4c2a-9600-9f1eb9ca1fc7, StackSetNotFoundException: StackSet TARGET_STACKSET not found
```

I am using `Rain v1.7.5 linux/amd64`.

It would be awesome if `rain` supported "service-managed" stacksets.

**Comment by ericzbeard** [comment]
The API has a CallAs parameter that we need to set, so I think this should require you to specify it on the command line.

`rain stackset ls --call-as admin`

The default for `call-as` will remain `self`

```
type CallAs string

// Enum values for CallAs
const (
	CallAsSelf           CallAs = "SELF"
	CallAsDelegatedAdmin CallAs = "DELEGATED_ADMIN"
)
```

Maybe simpler to do this:

`rain stackset ls --admin`

And assume self otherwise
