### ISSUE TITLE
Configurable colours

### ISSUE THREAD

**Issue by irgeek** [aws-cloudformation/rain#30]
I just found `rain` for the first time and it is awesome for working with the many, many CF stacks I currently manage. The only hiccup so far is the interaction between my terminal colours and the colours `rain` uses in output. I use the [light solarized](https://ethanschoonover.com/solarized/) which has a light yellow background (labeled _Base3_). The yellow used by `rain` is almost unreadable against that background:

![image](https://user-images.githubusercontent.com/57119/88869847-3916ba80-d257-11ea-993b-b82c56f9f774.png)

It would be great if we could configure the colours when the default ones don't work with our terminal colours.

**Comment by stilvoid** [comment]
I have a new version of Rain coming out quite soon which has a revamped UI. As part of this, I've changed some of the colours used and tested on dark and light terminal themes. You can check the preview [here](https://github.com/aws-cloudformation/rain/releases/tag/v1.0.0-preview).
