### ISSUE TITLE
Add a brew package

### ISSUE THREAD

**Issue by stilvoid** [aws-cloudformation/rain#31]
Installing Go packages can be non-trivial for people who don't use Go already. Brew will at least cover a good number of users.

**Comment by alock** [comment]
https://goreleaser.com/ is a great option for setting up homebrew.

**Comment by almorelle** [comment]
There's one isn't there?
https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/rain.rb

**Comment by stilvoid** [comment]
Yes, I just managed to get that merged last night. I'll close this Issue one it's merged into linuxbrew as well :)
