### ISSUE TITLE
Add flag to deploy command to not format the template

### ISSUE THREAD

**Issue by ericzbeard** [aws-cloudformation/rain#327]
### Discussed in https://github.com/aws-cloudformation/rain/discussions/326

<div type='discussions-op-text'>

<sup>Originally posted by **r-heimann** March 19, 2024</sup>
See title, is this actually possible?</div>

**Comment by r-heimann** [comment]
Thank you for creating the issues.

As i've said in the discussion thread, it would be great to have this kind of option for the `rain deploy` command.
I've often come across situations in CDK where the produced CDK CloudFormation template is somehow broken and is causing a lot of wasted time in debugging the issue.
Before https://github.com/aws-cloudformation/rain/issues/319 i was under the impression that rain is not modifiying the original CloudFormation template, but it is doing something to it. Having the option to disable that would be great, as it would help us save time with debugging rain related CloudFormation issues.

Background: Before we migrated to rain we had a simple pipeline that utilized the aws cli to deploy the template to AWS, this didn't involve any modification of the "source" template and it worked great. But rain is such a force multiplier for us that i can't imagine working without it anymore.
