### ISSUE TITLE
build subcommand fails without active AWS session

### ISSUE THREAD

**Issue by corey-cole** [aws-cloudformation/rain#331]
Up until recently, rain operated in a disconnected mode.  The requirement to have an active AWS session in order to use `rain build` puts a damper on the ability to use the tool.  I can appreciate that the fancy GenAI capabilities need to phone home in order to work, but last month `rain build AWS::S3::Bucket AWS::S3::BucketPolicy` gave appropriate results without needing a valid session.

Enhancement Request:  Add an `offline` flag so that users can continue to work with rain as they did up until February of this year.

**Comment by ericzbeard** [comment]
Try this in v1.8.2. In this version, we cache all of the schemas in the binary itself, and it only makes an SDK call to the registry if you try a type that we don't support (like a 3p resource). If it *does* still require a session, please let me know.
