### ISSUE TITLE
Support Git Sync deployment file for parameter and tag values

### ISSUE THREAD

**Issue by paul-e-allen** [aws-cloudformation/rain#351]
The `rain` configuration file for parameters and tags is very, very, very similar to the "stack deployment file" used by the Git Sync CloudFormation deployment process. It would be great if `rain` could accept the `parameters` and `tags` attributes from the git sync stack deployment file as the `Parameters` and `Tags` attributes in the current `rain` configuration file. It seems that only the capitalization of those two attributes is preventing `rain` from using a git sync stack deployment file (assuming that `rain` could/would ignore the `template-file-path` attribute) for parameter and tag values.

The use case is this: Use `rain` to bootstrap the creation of a CloudFormation stack, and then shift over to git sync management of the stack once the stack is created. Right now, two different parameter/tag files are required for this--one for `rain` and one for git sync. It would be great to have both approaches could use the same file. 

Even when using git sync for deployment, `rain` is a great tool to have while developing CloudFormation templates that are already or will be integrated with the git sync deployment process.

Documentation for the git sync stack deployment file: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/git-sync-concepts-terms.html#git-sync-concepts-terms-depoyment-file

**Comment by ericzbeard** [comment]
Sounds like a good idea, and a simple change.

**Comment by ericzbeard** [comment]
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/git-sync-concepts-terms.html#git-sync-concepts-terms-depoyment-file
