### ISSUE TITLE
Referencing implicit resource, `AWS::Serverless::ServerlessRestApi`, causes an error in Rain

### ISSUE THREAD

**Issue by ConnorKirk** [aws-cloudformation/rain#39]
When using SAM, the `ServerlessRestApi` resource is created in the transformation. It can be referenced in the template, but is not explicitly defined.

Rain produces the following error when deploying a template with the `AWS::Serverless::ServerlessRestApi` resource
`Error: template has unresolved dependency 'ServerlessRestApi' at Outputs: api`

**Comment by stilvoid** [comment]
Will be fixed in the next release. In short, rain was formatting templates before submitting to the CloudFormation service. This is unecessary so I have removed that behaviour.
