### ISSUE TITLE
User Supplied Change Set Name

### ISSUE THREAD

**Issue by georgealton** [aws-cloudformation/rain#448]
In my CI workflows I use the ChangeSet Name to describe Resource Property differences to display the before/after as a diff, and generate an AWS SSO Console Link directly to the ChangeSet with the ChangeSet Id.

To do this I need to know the ChangeSet Name, it would be a challenge to use rain in this workflow at the moment because rain generates a non deterministic changeset name, guessing at this would be messy and could run into issues where users are concurrently creating changesets.

https://github.com/aws-cloudformation/rain/blob/af424def0595608e5870238e99df7c3979dfd183/internal/aws/cfn/cfn.go#L292

It would help my workflow if I could supply the ChangeSet Name for rain to use.

When I naively tried to do this with my first glance at the docs I assumed it would be achieved with the interface being 

`rain deploy <template> --changeset <stackName> <changeSetName> --no-exec`

rain would have to watch for errors where a named changeset already exists, and fail appropriately.

**Comment by ericzbeard** [comment]
https://github.com/aws-cloudformation/rain/releases/tag/v1.12.0
