### ISSUE TITLE
Support python bindings

### ISSUE THREAD

**Issue by georgettica** [aws-cloudformation/rain#481]
I found rain to be super useful for converting template.yaml to an object I can parse using traditional json tools.

I want to integrate it into `jc` (see [issue](https://github.com/kellyjonbrazil/jc/issues/580)) and would like to get a python code to "marshal" `template.yaml` files

maybe even add the parameters to populate the object with the values.

if my request is too bizzare I will back down.

for reference, I tried other tools that were less up-to-date and they didn't have such marvelous results.

current code snippet that works for me (and is exactly what I need to extract)

```go
package main

import (
    "encoding/json"
    "fmt"
    "github.com/aws-cloudformation/rain/cft/parse"
)

func main() {
    template, err := parse.String(`
    <enter template here or pull from file>
    `)
     if errr != nil {
        fmt.Println(errr)
    }
    templateMap := template.Map()
    templateJson, errr := json.Marshal(templateMap)
    if errr != nil {
        fmt.Println(errr)
    }
    fmt.Println(string(templateJson))
}

**Comment by ericzbeard** [comment]
I'm not sure I understand exactly what you are asking for. Can you elaborate?

**Comment by ericzbeard** [comment]
Take a look at [cfn-lint](https://github.com/aws-cloudformation/cfn-lint) to see how it does YAML parsing. It's written in Python and actively maintained.
