### ISSUE TITLE
Specify CloudFormation Tags

### ISSUE THREAD

**Issue by cfarrend** [aws-cloudformation/rain#5]
Hey, not sure if I have missed something but it seems we can't deploy to CloudFormation with tags yet

I'm guessing it would be something involving adding a `Tags` list for both `createStack` & `updateStack` functions

**Comment by stilvoid** [comment]
You're not missing anything, I'm planning to implement this feature soon.

**Comment by stilvoid** [comment]
Fixed in 5494f047f0b0faf6db4f9fad6c4e06634bcb0430. I'll roll out a new version soon.
