### ISSUE TITLE
Support linux/arm64

### ISSUE THREAD

**Issue by georgealton** [aws-cloudformation/rain#515]
Hi, 
I've recently changed workflow, and now run ashai fedora remix distribution on apple silicon. Would love to run rain, and I've been building locally to keep working with rain.

Would you accept a PR that adds 'linux/arm64' as platform?

https://github.com/aws-cloudformation/rain/blob/b5685eb05cf412acb35addcb567f0d1742792a73/.github/workflows/build.sh#L5

Thanks!

**Comment by ericzbeard** [comment]
Yes please!
