### ISSUE TITLE
Changeset failing with "specified bucket does not exist" in GovCloud

### ISSUE THREAD

**Issue by davidsuehring** [aws-cloudformation/rain#538]
When deploying a large template (136k) to us-gov-west-1, rain fails with the following error: 

> error creating changeset: S3 error: The specified bucket does not exist

version - 1.15.0
command - 

> ./rain deploy my_template.yml my_stack \
>     --region us-gov-west-1 \
>     --role-arn arn:aws-us-gov:iam::XXXXXXXXXXXX:role/my_execution_role \
>     --s3-bucket my_bucket-XXXXXXXXXXXX-us-gov-west-1 \
>     --s3-prefix my_prefix \
>     --yes

Templates under 50k deploy successfully with the same command

**Comment by davidsuehring** [comment]
I think the constructed object URL is incorrect for the upload into S3, similar to #213, and that GovCloud requires a regional endpoint to be used, rather than the legacy global endpoint

**Comment by davidsuehring** [comment]
@ericzbeard I opened a PR that resolved this for me locally.

**Comment by ericzbeard** [comment]
PR merged, thanks for the fix! Hoping to get a release out in the next few days.
