### ISSUE TITLE
latest release has no binaries on it, breaking deploys

### ISSUE THREAD

**Issue by allixsenos** [aws-cloudformation/rain#543]
the latest release has no binaries attached

```
Run gh release download -R aws-cloudformation/rain --pattern '*_linux-amd64.zip' -D $RUNNER_TOOL_CACHE
no assets to download
```

womp womp :(

**Comment by allixsenos** [comment]
I see 1.16.1 but it's not marked latest

**Comment by ericzbeard** [comment]
Oh that's odd. The 1.16.0 release failed due to a github action being deprecated. Not sure why the next one wasn't marked as latest.

**Comment by ericzbeard** [comment]
Updated
