### ISSUE TITLE
Support for Change Sets

### ISSUE THREAD

**Issue by default50** [aws-cloudformation/rain#6]
Showing the diff befor updating is good, but I'd love to see a flag (being default enabled or not, up to discussion) that allows to create a Change Set [1] and inspect it before updating.

Thanks!

[1] https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-changesets.html

**Comment by stilvoid** [comment]
Great idea and I've been meaning to do this for a while. It will be in the next release :)
