### ISSUE TITLE
rain pkg - flag to write output to a file

### ISSUE THREAD

**Issue by asantos-fuze** [aws-cloudformation/rain#60]
At the moment when running `rain pkg <template>` the output is written to stdout.
It would be a nice feature to have a flag to write the output to a file.
For now I'm using redirect `>` as a work around for this

**Comment by stilvoid** [comment]
Good idea and an easy one to implement. I'll get this into the next release :+1:

**Comment by stilvoid** [comment]
Fixed in 4ccabedd9c696b689a4d017df5020be2e158cf84
