### ISSUE TITLE
cfn-lint shows "illegal function Fn::Rain::Embed [E3002]"

### ISSUE THREAD

**Issue by kyptov** [aws-cloudformation/rain#66]
I use cfn-lint in IDE and I wanted to try rain. I added !Rain::Embed and cfn-lint is not happy with this. 
Have plans to commit templates with "!Rain::*" to use "rain pkg" inside CI/CD.

Is this possible to somehow tell to cfn-lint that this function is legal?
I checked rain repository for any clue, but found nothing. 

In cfn-lint repo I found possibility to override resources spec, but not found how to add custom functions.

P.s. tool is great

**Comment by stilvoid** [comment]
I think this would need a change in cfn-lint as I'm not sure there's anything I can do from Rain to stop cfn-lint not knowing about the customer `Rain::` funcs.
