### ISSUE TITLE
Feature Request: Merge CFN templates into single template

### ISSUE THREAD

**Issue by jpbarto** [aws-cloudformation/rain#79]
CloudFormation templates can get lengthy which reduces readability of the template.  Nested stacks can be an answer for this, allowing developers to write numerous small templates, but then they need to manage the scope of parameters, passing them from a main template into child templates.

Could another approach be to take smaller CloudFormation templates, perhaps even partial templates, and merge them into a single template before sending them to the CFN service?  A behavior similar to Terraform where any `.tf` file in the current working directory is ingested by the tool.  

Another tool, implemented in Ruby, can be found on GitHub which merges multiple templates into a single template: https://github.com/ajrosen/AWS/tree/master/mkstack

What does this team think of such a feature?

**Comment by tam0ri** [comment]
Is [merge](https://aws-cloudformation.github.io/rain/rain_merge.html) sub commnd suitable for your usecase?

**Comment by jpbarto** [comment]
That will do quite nicely, thank you!
