### ISSUE TITLE
Better visuals for nested stacks

### ISSUE THREAD

**Issue by matteofigus** [aws-cloudformation/rain#8]
When deploying a stack with many nested stacks, I only can track the progress of the whole stack, without details about the underlining resources.
It would be cool if I could see some of that, when a nested stack would transit to a "in progress" state, with an auto-collapse feature when moving back to a "complete" state.

What do you think?

**Comment by stilvoid** [comment]
Yep, I like it. I want to improve the live update view while deploying in general as it's currently not very useful when you have lots of resources in your stack

**Comment by stilvoid** [comment]
v1 onwards has an overhauled display for nested stacks and more improvements to come once I've fully added nested changeset support (pending some questions I have with the CloudFormation service team)
