### ISSUE TITLE
Feature Request: Support AWS::OpenSearchService::Domain

### ISSUE THREAD

**Issue by noid11** [aws-cloudformation/rain#80]
## Description

- rain doesn't seem to support OpenSearch Domain resources, at least in version 1.2.0
- I did not find any existing similar issues, so I report this issue for visibility.

## Ref

AWS::OpenSearchService::Domain - AWS CloudFormation  
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-opensearchservice-domain.html

## my env

```bash
% sw_vers
ProductName:	macOS
ProductVersion:	12.2.1
BuildVersion:	21D62
% rain -v
Rain v1.2.0 darwin/amd64
% rain build AWS::OpenSearchService::Domain > template.yaml
No resource type found matching 'AWS::OpenSearchService::Domain'
% rain build --list | grep earch 
AWS::Elasticsearch::Domain
```

**Comment by tam0ri** [comment]
Just FYI:

[Spec file](https://github.com/aws-cloudformation/rain/blob/main/cft/spec/cfn.go) is generated by [script](https://github.com/aws-cloudformation/rain/blob/main/cft/spec/internal/main.go) automatically. It refers public AWS CloudFormation resource specification.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html

I guess the latest spec will be reflected at the next release.

**Comment by stilvoid** [comment]
Next release is coming soon. I've refreshed the spec and the this resource is in `main` now :+1:
