### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by kai2nenobu** [aws-cloudformation/rain#88]
`main` branch has many changes (https://github.com/aws-cloudformation/rain/compare/v1.2.0...7c1f2e2) and unreleased attractive features from v1.2.0.

I would appreciate it if a new version (v1.3.0?) is released.

**Comment by ugwis** [comment]
If you’re Go developer and can't wait for next release, you can also use `GO111MODULE=on go get github.com/aws-cloudformation/rain/cmd/rain@latest`

**Comment by kai2nenobu** [comment]
@ugwis Thank you for your suggestion.

In Go 1.19, `go install github.com/aws-cloudformation/rain/cmd/rain@main` does the work. (`go install github.com/aws-cloudformation/rain/cmd/rain@latest` installs version `1.2.0` instead of latest commit.)

**Comment by ericzbeard** [comment]
We created a new release for [1.3.2](https://github.com/aws-cloudformation/rain/releases/tag/v1.3.2), but haven't updated brew yet.

**Comment by jiegec** [comment]
> We created a new release for [1.3.2](https://github.com/aws-cloudformation/rain/releases/tag/v1.3.2), but haven't updated brew yet.

The version in `rain` cli is not updated:

```shell
$ rain --version
Rain v1.3.0 linux/arm64
```

**Comment by kai2nenobu** [comment]
[Homebrew package](https://github.com/Homebrew/homebrew-core/blob/master/Formula/rain.rb) already uses version 1.3.2. However, `rain --version` prints `v1.3.0` even if `rain` version is 1.3.2.

Anyway, thanks to releasing a new version. I think this issue is resolved.

**Comment by ericzbeard** [comment]
@kai2nenobu Thanks for pointing that out! I'll have to create 1.3.3 to fix it for brew.
