### ISSUE TITLE
Add support for stack sets

### ISSUE THREAD

**Issue by ericzbeard** [aws-cloudformation/rain#89]
It would be nice to have similar functionality to `rain deploy` for stack sets.

**Comment by skrisyuk** [comment]
Working on stackset ls command first...

**Comment by skrisyuk** [comment]
Draft version of "rain stackset ls" was added. Working on deploy and rm command.

**Comment by ericzbeard** [comment]
Can you create a draft PR so we can see progress?

**Comment by skrisyuk** [comment]
Draft version of deploy was added. Configuration file is required for stack set instances creation(see sample).

**Comment by skrisyuk** [comment]
Initial verson of update stack set was added
